name: Lint Workflow

on:
  pull_request:
    branches:
      - main
      - feature

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier Check
        id: prettier-check
        run: npx prettier . --check
        continue-on-error: true

      - name: Run Prettier Format
        if: steps.prettier-check.outcome == 'failure'
        run: npx prettier . --write

      - name: Run Linting
        run: npm run lint

      - name: Send Notification to Microsoft Teams
        run: |
          COMMITTER="$(git log -1 --pretty=format:'%an')"
          REPO="${GITHUB_REPOSITORY}"
          BRANCH="${GITHUB_HEAD_REF}"
          MESSAGE="Deployment to *${BRANCH}* branch of *${REPO}* by ${COMMITTER} has completed successfully!"
          PAYLOAD="{\"text\":\"$MESSAGE\"}"
          curl -H "Content-Type: application/json" -d "$PAYLOAD" "${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URL }}"

        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
